version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10.16.0
commands:
  gatsby-build-storybook-build:
    steps:
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install && npm rebuild
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - restore_cache:
          keys:
            - gatsby-public-cache-{{ .Branch }}
      - run:
          name: Gatsby Build
          command: GATSBY_CPU_COUNT=2 yarn build
      - save_cache:
          key: gatsby-public-cache-{{ .Branch }}
          paths:
            - ./public
      - restore_cache:
          keys:
            - v1-storybook-public-cache-{{ .Branch }}
      - run:
          name: Storybook Build
          command: yarn build-storybook
      - store_artifacts:
          path: ./storybook-static
      - save_cache:
          key: v1-storybook-public-cache-{{ .Branch }}
          paths:
            - ./storybook-static

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
      - release:
          filters:
            branches:
              only:
                - develop
jobs:
  build:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install JQ
          command: sudo apt-get install jq
      - run:
          name: Create GitHub Storybook Deployment
          command: ./tasks/deployment/storybook-deploy-start.sh > storybook_deployment
      - run:
          name: Create GitHub Gatsby Deployment
          command: ./tasks/deployment/gatsby-deploy-start.sh > gatsby_deployment
      - gatsby-build-storybook-build
      - run:
          name: Add GitHub Storybook Deployment success status
          command: ./tasks/deployment/storybook-deploy-end.sh success
          when: on_success
      - run:
          name: Add GitHub Storybook Deployment error status
          command: ./tasks/deployment/storybook-deploy-end.sh error
          when: on_fail
      - run:
          name: Add GitHub Gatsby Deployment success status
          command: ./tasks/deployment/gatsby-deploy-end.sh success
          when: on_success
      - run:
          name: Add GitHub Gatsby Deployment error status
          command: ./tasks/deployment/gatsby-deploy-end.sh error
          when: on_fail
      - run:
          name: Check lint error
          command: yarn lint
  # '      - run:
  #           name: Testing
  #           command: yarn ci-test'

  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - gatsby-build-storybook-build
      - run:
          name: Check lint error
          command: yarn lint
